name: permission_manager
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2
  meta: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.1

dependency_overrides:
  meta: ^1.8.0
