name: flutter_cache_manager
description: Generic cache manager for flutter. Saves web files on the storages of the device and saves the cache info using sqflite.
version: 3.3.0
homepage: https://github.com/Baseflow/flutter_cache_manager/tree/master/flutter_cache_manager

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  clock: ^1.1.0
  collection: ^1.15.0
  dio: ^4.0.6
  file: ">=6.0.0 <7.0.0"
  flutter:
    sdk: flutter
  http: ^0.13.4
  path: ^1.8.0
  path_provider: ^2.0.9
  pedantic: ^1.11.1
  rxdart: ">=0.26.0 <0.28.0"
  sqflite: ^2.0.2+1
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.10
  mockito: ^5.1.0
